# Generated by Django 2.2.4 on 2019-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
